/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcknowledgementReceiptsRouteImport } from './routes/acknowledgement-receipts'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as QuotationRouteImport } from './routes/quotation'
import { Route as AcknowledgementReceiptsNewRouteImport } from './routes/acknowledgement-receipts_.new'
import { Route as BillingNewRouteImport } from './routes/billing_.new'
import { Route as QuotationNewRouteImport } from './routes/quotation_.new'
import { Route as AcknowledgementReceiptsIdEditRouteImport } from './routes/acknowledgement-receipts_.$id.edit'
import { Route as BillingIdEditRouteImport } from './routes/billing_.$id.edit'
import { Route as QuotationIdEditRouteImport } from './routes/quotation_.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcknowledgementReceiptsRoute = AcknowledgementReceiptsRouteImport.update({
  id: '/acknowledgement-receipts',
  path: '/acknowledgement-receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationRoute = QuotationRouteImport.update({
  id: '/quotation',
  path: '/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const AcknowledgementReceiptsNewRoute =
  AcknowledgementReceiptsNewRouteImport.update({
    id: '/acknowledgement-receipts_/new',
    path: '/acknowledgement-receipts/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const BillingNewRoute = BillingNewRouteImport.update({
  id: '/billing_/new',
  path: '/billing/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationNewRoute = QuotationNewRouteImport.update({
  id: '/quotation_/new',
  path: '/quotation/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AcknowledgementReceiptsIdEditRoute =
  AcknowledgementReceiptsIdEditRouteImport.update({
    id: '/acknowledgement-receipts_/$id/edit',
    path: '/acknowledgement-receipts/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const BillingIdEditRoute = BillingIdEditRouteImport.update({
  id: '/billing_/$id/edit',
  path: '/billing/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationIdEditRoute = QuotationIdEditRouteImport.update({
  id: '/quotation_/$id/edit',
  path: '/quotation/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acknowledgement-receipts': typeof AcknowledgementReceiptsRoute
  '/billing': typeof BillingRoute
  '/contracts': typeof ContractsRoute
  '/quotation': typeof QuotationRoute
  '/acknowledgement-receipts/new': typeof AcknowledgementReceiptsNewRoute
  '/billing/new': typeof BillingNewRoute
  '/quotation/new': typeof QuotationNewRoute
  '/acknowledgement-receipts/$id/edit': typeof AcknowledgementReceiptsIdEditRoute
  '/billing/$id/edit': typeof BillingIdEditRoute
  '/quotation/$id/edit': typeof QuotationIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acknowledgement-receipts': typeof AcknowledgementReceiptsRoute
  '/billing': typeof BillingRoute
  '/contracts': typeof ContractsRoute
  '/quotation': typeof QuotationRoute
  '/acknowledgement-receipts/new': typeof AcknowledgementReceiptsNewRoute
  '/billing/new': typeof BillingNewRoute
  '/quotation/new': typeof QuotationNewRoute
  '/acknowledgement-receipts/$id/edit': typeof AcknowledgementReceiptsIdEditRoute
  '/billing/$id/edit': typeof BillingIdEditRoute
  '/quotation/$id/edit': typeof QuotationIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acknowledgement-receipts': typeof AcknowledgementReceiptsRoute
  '/billing': typeof BillingRoute
  '/contracts': typeof ContractsRoute
  '/quotation': typeof QuotationRoute
  '/acknowledgement-receipts_/new': typeof AcknowledgementReceiptsNewRoute
  '/billing_/new': typeof BillingNewRoute
  '/quotation_/new': typeof QuotationNewRoute
  '/acknowledgement-receipts_/$id/edit': typeof AcknowledgementReceiptsIdEditRoute
  '/billing_/$id/edit': typeof BillingIdEditRoute
  '/quotation_/$id/edit': typeof QuotationIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acknowledgement-receipts'
    | '/billing'
    | '/contracts'
    | '/quotation'
    | '/acknowledgement-receipts/new'
    | '/billing/new'
    | '/quotation/new'
    | '/acknowledgement-receipts/$id/edit'
    | '/billing/$id/edit'
    | '/quotation/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acknowledgement-receipts'
    | '/billing'
    | '/contracts'
    | '/quotation'
    | '/acknowledgement-receipts/new'
    | '/billing/new'
    | '/quotation/new'
    | '/acknowledgement-receipts/$id/edit'
    | '/billing/$id/edit'
    | '/quotation/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/acknowledgement-receipts'
    | '/billing'
    | '/contracts'
    | '/quotation'
    | '/acknowledgement-receipts_/new'
    | '/billing_/new'
    | '/quotation_/new'
    | '/acknowledgement-receipts_/$id/edit'
    | '/billing_/$id/edit'
    | '/quotation_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcknowledgementReceiptsRoute: typeof AcknowledgementReceiptsRoute
  BillingRoute: typeof BillingRoute
  ContractsRoute: typeof ContractsRoute
  QuotationRoute: typeof QuotationRoute
  AcknowledgementReceiptsNewRoute: typeof AcknowledgementReceiptsNewRoute
  BillingNewRoute: typeof BillingNewRoute
  QuotationNewRoute: typeof QuotationNewRoute
  AcknowledgementReceiptsIdEditRoute: typeof AcknowledgementReceiptsIdEditRoute
  BillingIdEditRoute: typeof BillingIdEditRoute
  QuotationIdEditRoute: typeof QuotationIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acknowledgement-receipts': {
      id: '/acknowledgement-receipts'
      path: '/acknowledgement-receipts'
      fullPath: '/acknowledgement-receipts'
      preLoaderRoute: typeof AcknowledgementReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation': {
      id: '/quotation'
      path: '/quotation'
      fullPath: '/quotation'
      preLoaderRoute: typeof QuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acknowledgement-receipts_/new': {
      id: '/acknowledgement-receipts_/new'
      path: '/acknowledgement-receipts/new'
      fullPath: '/acknowledgement-receipts/new'
      preLoaderRoute: typeof AcknowledgementReceiptsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing_/new': {
      id: '/billing_/new'
      path: '/billing/new'
      fullPath: '/billing/new'
      preLoaderRoute: typeof BillingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation_/new': {
      id: '/quotation_/new'
      path: '/quotation/new'
      fullPath: '/quotation/new'
      preLoaderRoute: typeof QuotationNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acknowledgement-receipts_/$id/edit': {
      id: '/acknowledgement-receipts_/$id/edit'
      path: '/acknowledgement-receipts/$id/edit'
      fullPath: '/acknowledgement-receipts/$id/edit'
      preLoaderRoute: typeof AcknowledgementReceiptsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing_/$id/edit': {
      id: '/billing_/$id/edit'
      path: '/billing/$id/edit'
      fullPath: '/billing/$id/edit'
      preLoaderRoute: typeof BillingIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation_/$id/edit': {
      id: '/quotation_/$id/edit'
      path: '/quotation/$id/edit'
      fullPath: '/quotation/$id/edit'
      preLoaderRoute: typeof QuotationIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcknowledgementReceiptsRoute: AcknowledgementReceiptsRoute,
  BillingRoute: BillingRoute,
  ContractsRoute: ContractsRoute,
  QuotationRoute: QuotationRoute,
  AcknowledgementReceiptsNewRoute: AcknowledgementReceiptsNewRoute,
  BillingNewRoute: BillingNewRoute,
  QuotationNewRoute: QuotationNewRoute,
  AcknowledgementReceiptsIdEditRoute: AcknowledgementReceiptsIdEditRoute,
  BillingIdEditRoute: BillingIdEditRoute,
  QuotationIdEditRoute: QuotationIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
